### ISSUE TITLE
Enable evaluation on epoch with max validation acc.

### ISSUE THREAD

**Issue by nelson-liu** [allenai/deep_qa#189]
~~I think model loading is broken right now due to custom layers, but I would need to write a test and check. Until we fix model loading,~~ we can't evaluate on test set with the epoch of a model that had the max validation accuracy (done by serializing then reloading said epoch).

We also need hooks in the scala code to use these in experiments, and make sure the evaluation output is correct with it.

**Comment by nelson-liu** [comment]
Model loading was recently fixed, so updating this issue. #181 has some work in evaluating on test et data in the python code, but it'd be good to be able to evaluate with the highest performing epoch (as opposed to the last epoch, which it's doing now). In addition, it'd be nice to be able to specify a test file in the scala experiments code. This would also require rewriting the functions that parse the output from an experiment (i.e. accuracy and such).

**Comment by matt-gardner** [comment]
Fixed by #302
