### ISSUE TITLE
Why ReadMe.md haven't mention the doc's url and No install instructions?

### ISSUE THREAD

**Issue by liyi193328** [allenai/deep_qa#280]
Hi, as the title.
I know the doc url is http://deep-qa.readthedocs.io/en/latest/models/about_models.html, but I suggest place it in the ReadMe.
To use the liabrary , I must add project path to PYTHONPATH manully?

**Comment by matt-gardner** [comment]
Thanks, that's a good suggestion.  You can get to the docs by clicking on the docs badge at the top, but a more explicit link would be a good idea.  Care to submit a PR to add one?

As for installing this, we've [started the process](https://github.com/allenai/deep_qa/pull/210) to get this on pip, but haven't quite thought this is totally ready for a public release yet, so we haven't actually done it, or announced this project anywhere.  So, yes, you'll need to put this on your PYTHONPATH somehow for now.
