### ISSUE TITLE
Testing the model and getting answer to a new question 

### ISSUE THREAD

**Issue by marilenaoita** [allenai/deep_qa#413]
Hi, I have trained the bidaf model on squad, and I have the following questions 

1. predictions = score_dataset("[..]reading_comprehension/bidaf_squad.json")
gives: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: score_dataset() missing 1 required positional argument: 'dataset_files'
Another argument is required, and I try to add the path to the .tsvs, but it doesnt work. 

2. There is no information (at least explicit) in the documentation on how to get the answer to a new question. Could you give an example/specify the function to do this? thanks !

**Comment by DeNeutoy** [comment]
Hi there - DeepQA is not supported anymore. It has been superseded by [AllenNLP](https://github.com/allenai/allennlp), so unfortunately we aren't going to be able to help you. Please try using AllenNLP - you should find it considerably easier to use.
